apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: authnsvc
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: authnsvc
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ .Values.authn.serviceAccountName }}
roleRef:
  kind: Role
  name: authnsvc
  apiGroup: rbac.authorization.k8s.io
