apiVersion: v1
kind: Service
metadata:
  name: authn-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    component: authn-service
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.authn.apiPort }}
  - name: grpc
    protocol: TCP
    port: 8080
