apiVersion: v1
kind: Service
metadata:
  name: progress-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    component: progress-service
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.progress.apiPort }}