apiVersion: v1
kind: Service
metadata:
  name: setting-service-grpc
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  selector:
    component: setting-service
  ports:
  - name: grpc
    protocol: TCP
    port: 8080 
