apiVersion: v1
kind: Service
metadata:
  name: scenario-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    component: scenario-service
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.scenario.apiPort }}