apiVersion: v1
kind: Service
metadata:
  name: accesscode-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    component: accesscode-service
  ports:
  - name: grpc
    protocol: TCP
    port: {{ .Values.accesscode.grpcPort }}
