apiVersion: v1
kind: Service
metadata:
  name: vmset-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    component: vmset-service
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.vmset.apiPort }}