apiVersion: v1
kind: Service
metadata:
  name: vmtemplate-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    component: vmtemplate-service
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.vmtemplate.apiPort }}