apiVersion: v1
kind: Service
metadata:
  name: environment-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    component: environment-service
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.environment.apiPort }}