apiVersion: v1
kind: Service
metadata:
  name: session-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    component: session-service
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.session.apiPort }}