apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: accesscodes.hobbyfarm.io
  annotations:
    helm.sh/hook: crd-install
spec:
  group: hobbyfarm.io
  version: v1
  names:
    kind: AccessCode
    plural: accesscodes
  scope: Cluster