apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: virtualmachinesets.hobbyfarm.io
  annotations:
    helm.sh/hook: crd-install
spec:
  group: hobbyfarm.io
  version: v1
  names:
    kind: VirtualMachineSet
    plural: virtualmachinesets
  scope: Cluster
