apiVersion: v1
kind: Service
metadata:
  name: course-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    component: course-service
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.course.apiPort }}