apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: hobbyfarm-webhook
spec:
  selector:
    component: conversion-service
  ports:
  - name: webhook
    port: {{ .Values.conversion.servicePort }}
    targetPort: {{ .Values.conversion.containerPort }}