---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: authr-{{ .Release.Namespace }}
rules:
  - apiGroups: ["authorization.k8s.io"]
    resources: ["subjectaccessreviews"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: authr-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ .Values.authr.serviceAccountName }}
roleRef:
  kind: ClusterRole
  name: authr-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
