apiVersion: v1
kind: Service
metadata:
  name: authr-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    component: authr-service
  ports:
  - name: grpc
    protocol: TCP
    port: 8080
