{{ if .Values.ranchervm.enabled }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: ranchervm-role
rules:
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - "*"
- apiGroups: ["", "batch"]
  resources: ["pods", "nodes", "services", "jobs", "endpoints", "persistentvolumes", "persistentvolumeclaims"]
  verbs: ["*"]
- apiGroups: ["vm.rancher.io"]
  resources: ["virtualmachines", "arptables", "credentials", "settings", "machineimages"]
  verbs: ["*"]
{{ end }}