{{ if $.Values.guac }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guac
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      component: guac
  template:
    metadata:
      labels:
        component: guac
    spec:
      containers:
        - name: guac
          image: {{ $.Values.guac.image }}
{{ end }}