apiVersion: v1
kind: Service
metadata:
  name: scheduledevent-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    component: scheduledevent-service
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.scheduledevent.apiPort }}