apiVersion: v1
kind: Service
metadata:
  name: vm-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    component: vm-service
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.vm.apiPort }}