apiVersion: v1
kind: Service
metadata:
  name: vm-service-grpc
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  selector:
    component: vm-service
  ports:
  - name: grpc
    protocol: TCP
    port: 8080
