name: Publish

on:
  push:
    branches:
      - master
    paths:
      - '**/Chart.yaml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: check if version was bumped
      run: git diff HEAD~1 charts/hobbyfarm/Chart.yaml | grep 'version:'
    - name: package and release charts
      env:
        OWNER: ${{ github.repository_owner }}
        REPO: ${{ github.event.repository.name }}
        CR_TOKEN: ${{ secrets.CR_TOKEN }}
      run: |
        docker run -w /app --entrypoint /bin/sh -v $PWD:/app quay.io/helmpack/chart-releaser:v1.6.1 -c "
          git config --global --add safe.directory /app &&
          git config --global user.email 'action@github.com' &&
          git config --global user.name 'GitHub Action' &&
          cr package /app/charts/hobbyfarm --package-path /app/dir &&
          cr upload --owner $OWNER --git-repo $REPO --package-path /app/dir --token $CR_TOKEN --push &&
          cr index --owner $OWNER --git-repo $REPO --package-path /app/dir --index-path /app/docs/index.yaml --pages-index-path /docs/index.yaml --push --pages-branch master
        "
